### ISSUE TITLE
ETVPNManager connect不能正常连接

### ISSUE THREAD

**Issue by wangsongfeng** [jfdream/xray-ios-mac#2]
ETVPNManager在之前使用过程中正常使用，什么也没有改变的情况下，突然就连接失败了，请问一下是有什么限制吗，项目代码没有动，之前能用的手机安装成功后，再没有安装新的包，也是连接不成功

**Comment by superggh** [comment]
已经可以了

**Comment by jfdream** [comment]
The previous SDK upload error caused, has been repaired, it is recommended to adjust the system time to test it.

**Comment by jfdream** [comment]
The previous SDK upload error caused, has been repaired, it is recommended to adjust the system time to test it.
