### ISSUE TITLE
Unable to Run Project on iOS Simulator due to Missing Library in XCFramework

### ISSUE THREAD

**Issue by Pedro96906** [jfdream/xray-ios-mac#3]
Hello, I'm encountering an issue where the project is unable to run on the iOS Simulator. The specific error message is as follows:

.../xray-ios-mac/xFutureTunnel/Future.xcframework:1:1 While building for iOS Simulator, no library for this platform was found in '.../xray-ios-mac/xFutureTunnel/Future.xcframework'.

**Issue Details:**

Location: .../xray-ios-mac/xFutureTunnel/Future.xcframework
Error Line: 1:1
Error Message: While building for iOS Simulator, no library for this platform was found.

**Steps to Reproduce:**

Attempt to build and run the project on the iOS Simulator.
Encounter the mentioned error regarding the missing library in the XCFramework.
Expected Behavior:
The project should build and run successfully on the iOS Simulator without encountering the mentioned library-related issue.

**Comment by jfdream** [comment]
I have enabled the emulator to compile and function properly, but the VPN cannot be used on the emulator.
