### ISSUE TITLE
Persistent 'Update Required' Label in iOS VPN Settings

### ISSUE THREAD

**Issue by Pedro96906** [jfdream/xray-ios-mac#4]
**Overview:**
Our iOS VPN application is currently experiencing an issue where users see a persistent "Update Required" label in the VPN settings. This issue is affecting the user experience and requires attention to ensure proper functionality.

**Steps to Reproduce:**

Install on an iOS device.
Observe that the "Update Required" label appears in the iOS VPN settings and does not vanish.

**Expected Behavior:**
The "Update Required" label should disappear after the VPN profile is applied, providing a seamless user experience.

**Additional Information:**
This issue is observed on iOS devices running 16.6 and 16.3

Attachments:
![vpn](https://github.com/jfdream/xray-ios-mac/assets/151558996/24b7be4a-be2b-4790-a5b7-639a20684388)

**Comment by jfdream** [comment]
iPhone system version is below the configuration version of Xcode network extension, just make some modifications to network extension target.
