### ISSUE TITLE
关于xcode提示'ExtParser/ExtParser.h' file not found的问题

### ISSUE THREAD

**Issue by shusheng-l** [jfdream/xray-ios-mac#7]
开发者你好 首先感谢您对资源的分享 我第一次接触xcode开发 模拟器运行时提示'ExtParser/ExtParser.h' file not found 但是我看到路径中有这个文件 但是编译器好像没有将他自动包含进去 请问用什么办法可以解决这样的报错让他可以顺利在模拟器中运行起来呢

**Comment by jfdream** [comment]
The simulator can be compiled and run directly, but it does not support the use of VPN functions. Please open the xNetFuture.xcworkspace project.
