### ISSUE TITLE
分流配置问题

### ISSUE THREAD

**Issue by Timi2386** [jfdream/xray-ios-mac#8]
你好，请问iOS端支持自己配置分流规则吗，比如只想要访问指定的域名，其它域名则不可以访问

**Comment by Yan-jinwei** [comment]
请问是否支持使用.conf后缀名的文件

**Comment by jfdream** [comment]
已支持 xray 和 v2ray 的规则设置，参考下面方法，不支持 .conf 后缀文件，可以自己修改代码
-(void)setXrayRoutes:(NSArray <NSDictionary *> *)routes

**Comment by Timi2386** [comment]
你好，我在ViewController.m文件的viewDidLoad方法中，调用了setXrayRoutes方法，并分别设置了direct、proxy、block域名，在连接成功之后，均可以正常访问，这个配置似乎没有生效，iOS端与MacOS端均是如此
![1700795632663](https://github.com/jfdream/xray-ios-mac/assets/151816504/9f751ab1-0610-440e-bbd5-4e54454feafc)

**Comment by jfdream** [comment]
fixed

**Comment by Timi2386** [comment]
你好，我拉取了最新的代码，rules的配置似乎还是没有生效，我打印了ETProtocolParser工具中parseURI方法返回的内容，rules配置有在其中，但是在连接成功之后，访问对应的域名，还是可以正常访问，并没有按照我配置的规则进行处理

**Comment by Timi2386** [comment]
这是控制台打印的在连接时候outbounds配置和rules配置，也仔细对照了https://xtls.github.io/config的规则，实在看不出有啥问题😂

![1700819539663](https://github.com/jfdream/xray-ios-mac/assets/151816504/e7f2f86b-0bea-49db-ba28-e0396792cc0c)

**Comment by Timi2386** [comment]
这是控制台打印的在连接时候outbounds配置和rules配置，也仔细对照了路由规则，实在看不出有啥问题😂(https://xtls.github.io/config/routing.html#routingobject)

![1700819539663](https://github.com/jfdream/xray-ios-mac/assets/151816504/8d5d3e05-1ac0-4a86-8910-cb85994cc365)

**Comment by jfdream** [comment]
没有配置 app group id 导致的，demo 之前没有配置 app group，请参考最新代码配置 app group，并修改 app group id，有问题可以重新提交 issue，要不然看不到的。
